package com.cmrwebstudio.beer.entity;

public enum Category {
	BRITISH_ALE, IRISH_ALE, NORTH_AMERICAN_ALE, GERMAN_ALE, 
	BELGIAN_AND_FRENCH_ALE, INTERNATIONAL_ALE, GERMAN_LAGER, NORTH_AMERICAN_LAGER,
	OTHER_LAGER, INTERNATIONAL_LAGER, OTHER_CATEGORY, UNSPECIFIED
}
